name: deploy-site
on:
  push:
    branches: 
      - main

jobs:
  publish-content:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4.0.0
        with:
          python-version: 3.8.9
      - name: Install Dependencies
        run: |
          python -m pip install -U pip 
          python -m pip install -r requirements.txt
      - name: Build the Static Content
        run: make publish
      - name: Add nojekyll
        run: |
          touch ./output/.nojekyll
      - name: Set URL
        run: git remote set-url --push origin "https://:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Static Content to Github Pages
        run: make github
